import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { zustandSafeStorage } from './safeStorage';

type Lang = 'en' | 'sw';

const translations: Record<string, Record<Lang, string>> = {
  // ── UI actions ──────────────────────────────────────────────────────────────
  welcome:              { en: 'Welcome',                sw: 'Karibu' },
  login:                { en: 'Sign In',                sw: 'Ingia' },
  logout:               { en: 'Sign Out',               sw: 'Toka' },
  save:                 { en: 'Save',                   sw: 'Hifadhi' },
  cancel:               { en: 'Cancel',                 sw: 'Ghairi' },
  delete:               { en: 'Delete',                 sw: 'Futa' },
  edit:                 { en: 'Edit',                   sw: 'Hariri' },
  add:                  { en: 'Add',                    sw: 'Ongeza' },
  search:               { en: 'Search',                 sw: 'Tafuta' },
  loading:              { en: 'Loading...',              sw: 'Inapakia...' },
  error:                { en: 'Error',                  sw: 'Hitilafu' },
  submit:               { en: 'Submit',                 sw: 'Wasilisha' },
  approve:              { en: 'Approve',                sw: 'Idhini' },
  reject:               { en: 'Reject',                 sw: 'Kataa' },
  pending:              { en: 'Pending',                sw: 'Inasubiri' },
  approved:             { en: 'Approved',               sw: 'Imeidhinishwa' },
  rejected:             { en: 'Rejected',               sw: 'Imekataliwa' },
  balance:              { en: 'Balance',                sw: 'Salio' },
  amount:               { en: 'Amount',                 sw: 'Kiasi' },
  date:                 { en: 'Date',                   sw: 'Tarehe' },
  name:                 { en: 'Name',                   sw: 'Jina' },
  class:                { en: 'Class',                  sw: 'Darasa' },
  subject:              { en: 'Subject',                sw: 'Somo' },
  marks:                { en: 'Marks',                  sw: 'Alama' },
  grade:                { en: 'Grade',                  sw: 'Daraja' },
  absent:               { en: 'Absent',                 sw: 'Hayupo' },
  present:              { en: 'Present',                sw: 'Yuko' },
  late:                 { en: 'Late',                   sw: 'Amechelewa' },
  progress:             { en: 'Progress',               sw: 'Maendeleo' },
  alerts:               { en: 'Alerts',                 sw: 'Tahadhari' },

  // ── Common buttons & actions ─────────────────────────────────────────────
  'View':               { en: 'View',                   sw: 'Ona' },
  'Download':           { en: 'Download',               sw: 'Pakua' },
  'Upload':             { en: 'Upload',                 sw: 'Pakia' },
  'Print':              { en: 'Print',                  sw: 'Chapisha' },
  'Export':             { en: 'Export',                 sw: 'Hamisha' },
  'Import':             { en: 'Import',                 sw: 'Ingiza' },
  'Send':               { en: 'Send',                   sw: 'Tuma' },
  'Publish':            { en: 'Publish',                sw: 'Chapisha' },
  'Unpublish':          { en: 'Unpublish',              sw: 'Ondoa Uchapishaji' },
  'Close':              { en: 'Close',                  sw: 'Funga' },
  'Back':               { en: 'Back',                   sw: 'Rudi' },
  'Next':               { en: 'Next',                   sw: 'Mbele' },
  'Previous':           { en: 'Previous',               sw: 'Nyuma' },
  'Filter':             { en: 'Filter',                 sw: 'Chuja' },
  'Reset':              { en: 'Reset',                  sw: 'Weka Upya' },
  'Refresh':            { en: 'Refresh',                sw: 'Onyesha Upya' },
  'Confirm':            { en: 'Confirm',                sw: 'Thibitisha' },
  'Yes':                { en: 'Yes',                    sw: 'Ndio' },
  'No':                 { en: 'No',                     sw: 'Hapana' },
  'All':                { en: 'All',                    sw: 'Wote' },
  'None':               { en: 'None',                   sw: 'Hakuna' },
  'Select':             { en: 'Select',                 sw: 'Chagua' },
  'Update':             { en: 'Update',                 sw: 'Sasisha' },
  'Create':             { en: 'Create',                 sw: 'Tengeneza' },
  'Generate':           { en: 'Generate',               sw: 'Tengeneza' },
  'Mark':               { en: 'Mark',                   sw: 'Weka Alama' },
  'Actions':            { en: 'Actions',                sw: 'Vitendo' },
  'Details':            { en: 'Details',                sw: 'Maelezo' },
  'Summary':            { en: 'Summary',                sw: 'Muhtasari' },
  'Report':             { en: 'Report',                 sw: 'Ripoti' },
  'New':                { en: 'New',                    sw: 'Mpya' },
  'Add New':            { en: 'Add New',                sw: 'Ongeza Mpya' },
  'Save Changes':       { en: 'Save Changes',           sw: 'Hifadhi Mabadiliko' },
  'Export CSV':         { en: 'Export CSV',             sw: 'Hamisha CSV' },
  'Export PDF':         { en: 'Export PDF',             sw: 'Hamisha PDF' },
  'Download PDF':       { en: 'Download PDF',           sw: 'Pakua PDF' },
  'Bulk Import':        { en: 'Bulk Import',            sw: 'Ingiza Wingi' },
  'No data found':      { en: 'No data found',          sw: 'Hakuna data' },
  'No records found':   { en: 'No records found',       sw: 'Hakuna rekodi' },

  // ── Common form labels ────────────────────────────────────────────────────
  'First Name':         { en: 'First Name',             sw: 'Jina la Kwanza' },
  'Last Name':          { en: 'Last Name',              sw: 'Jina la Familia' },
  'Full Name':          { en: 'Full Name',              sw: 'Jina Kamili' },
  'Email':              { en: 'Email',                  sw: 'Barua Pepe' },
  'Email Address':      { en: 'Email Address',          sw: 'Anwani ya Barua Pepe' },
  'Phone':              { en: 'Phone',                  sw: 'Simu' },
  'Phone Number':       { en: 'Phone Number',           sw: 'Nambari ya Simu' },
  'Address':            { en: 'Address',                sw: 'Anwani' },
  'Password':           { en: 'Password',               sw: 'Nywila' },
  'Gender':             { en: 'Gender',                 sw: 'Jinsia' },
  'Male':               { en: 'Male',                   sw: 'Mwanaume' },
  'Female':             { en: 'Female',                 sw: 'Mwanamke' },
  'Date of Birth':      { en: 'Date of Birth',          sw: 'Tarehe ya Kuzaliwa' },
  'Blood Group':        { en: 'Blood Group',            sw: 'Kundi la Damu' },
  'Nationality':        { en: 'Nationality',            sw: 'Utaifa' },
  'Religion':           { en: 'Religion',               sw: 'Dini' },
  'Description':        { en: 'Description',            sw: 'Maelezo' },
  'Notes':              { en: 'Notes',                  sw: 'Maelezo' },
  'Comments':           { en: 'Comments',               sw: 'Maoni' },
  'Type':               { en: 'Type',                   sw: 'Aina' },
  'Status':             { en: 'Status',                 sw: 'Hali' },
  'Role':               { en: 'Role',                   sw: 'Wadhifu' },
  'Term':               { en: 'Term',                   sw: 'Muhula' },
  'Year':               { en: 'Year',                   sw: 'Mwaka' },
  'Academic Year':      { en: 'Academic Year',          sw: 'Mwaka wa Masomo' },
  'Title':              { en: 'Title',                  sw: 'Kichwa' },
  'Category':           { en: 'Category',               sw: 'Kikundi' },
  'Department':         { en: 'Department',             sw: 'Idara' },
  'Position':           { en: 'Position',               sw: 'Cheo' },

  // ── Status values ─────────────────────────────────────────────────────────
  'Active':             { en: 'Active',                 sw: 'Amilifu' },
  'Inactive':           { en: 'Inactive',               sw: 'Haifanyi Kazi' },
  'Suspended':          { en: 'Suspended',              sw: 'Amesimamishwa' },
  'Transferred':        { en: 'Transferred',            sw: 'Amehamishwa' },
  'Draft':              { en: 'Draft',                  sw: 'Rasimu' },
  'Published':          { en: 'Published',              sw: 'Imechapishwa' },
  'Completed':          { en: 'Completed',              sw: 'Imekamilika' },
  'Open':               { en: 'Open',                   sw: 'Wazi' },
  'Closed':             { en: 'Closed',                 sw: 'Imefungwa' },
  'Paid':               { en: 'Paid',                   sw: 'Imelipwa' },
  'Unpaid':             { en: 'Unpaid',                 sw: 'Haijalipiwa' },
  'Overdue':            { en: 'Overdue',                sw: 'Imechelewa' },
  'Partial':            { en: 'Partial',                sw: 'Sehemu' },
  'Passed':             { en: 'Passed',                 sw: 'Amefaulu' },
  'Failed':             { en: 'Failed',                 sw: 'Ameshindwa' },

  // ── Student-related strings ───────────────────────────────────────────────
  'Add Student':        { en: 'Add Student',            sw: 'Ongeza Mwanafunzi' },
  'Edit Student':       { en: 'Edit Student',           sw: 'Hariri Mwanafunzi' },
  'Delete Student':     { en: 'Delete Student',         sw: 'Futa Mwanafunzi' },
  'Student Name':       { en: 'Student Name',           sw: 'Jina la Mwanafunzi' },
  'Admission No':       { en: 'Admission No',           sw: 'Nambari ya Usajili' },
  'Admission Number':   { en: 'Admission Number',       sw: 'Nambari ya Usajili' },
  'Student Type':       { en: 'Student Type',           sw: 'Aina ya Mwanafunzi' },
  'Boarder':            { en: 'Boarder',                sw: 'Mwanafunzi wa Bweni' },
  'Full-Time Boarder':  { en: 'Full-Time Boarder',      sw: 'Mwanafunzi wa Bweni (Wiki Nzima)' },
  'Weekly Boarder':     { en: 'Weekly Boarder',         sw: 'Mwanafunzi wa Bweni (Wikiani)' },
  'Day Scholar':        { en: 'Day Scholar',            sw: 'Mwanafunzi wa Nje' },
  'Uses Transport':     { en: 'Uses Transport',         sw: 'Anatumia Usafiri' },
  'All Students':       { en: 'All Students',           sw: 'Wanafunzi Wote' },
  'By Class':           { en: 'By Class',               sw: 'Kwa Darasa' },
  'Total Students':     { en: 'Total Students',         sw: 'Jumla ya Wanafunzi' },
  'Enrolled Students':  { en: 'Enrolled Students',      sw: 'Wanafunzi Waliojisajili' },
  'New Admissions':     { en: 'New Admissions',         sw: 'Usajili Mpya' },
  'Student Details':    { en: 'Student Details',        sw: 'Maelezo ya Mwanafunzi' },
  'Parent/Guardian':    { en: 'Parent/Guardian',        sw: 'Mzazi/Mlezi' },

  // ── Teacher-related strings ───────────────────────────────────────────────
  'Add Teacher':        { en: 'Add Teacher',            sw: 'Ongeza Mwalimu' },
  'Edit Teacher':       { en: 'Edit Teacher',           sw: 'Hariri Mwalimu' },
  'Teacher Name':       { en: 'Teacher Name',           sw: 'Jina la Mwalimu' },
  'Employee Number':    { en: 'Employee Number',        sw: 'Nambari ya Mfanyakazi' },
  'Specialization':     { en: 'Specialization',         sw: 'Utaalamu' },
  'Total Teachers':     { en: 'Total Teachers',         sw: 'Jumla ya Walimu' },
  'Class Teacher':      { en: 'Class Teacher',          sw: 'Mwalimu wa Darasa' },

  // ── Attendance strings ────────────────────────────────────────────────────
  'Mark Attendance':    { en: 'Mark Attendance',        sw: 'Weka Mahudhurio' },
  'Attendance Report':  { en: 'Attendance Report',      sw: 'Ripoti ya Mahudhurio' },
  'Mark All Present':   { en: 'Mark All Present',       sw: 'Weka Wote Wako' },
  'Save Attendance':    { en: 'Save Attendance',        sw: 'Hifadhi Mahudhurio' },
  'Attendance Date':    { en: 'Attendance Date',        sw: 'Tarehe ya Mahudhurio' },
  'Attendance Rate':    { en: 'Attendance Rate',        sw: 'Kiwango cha Mahudhurio' },
  'Present Today':      { en: 'Present Today',          sw: 'Waliopo Leo' },
  'Absent Today':       { en: 'Absent Today',           sw: 'Hawapo Leo' },
  "Today's Attendance": { en: "Today's Attendance",     sw: 'Mahudhurio ya Leo' },
  'Period':             { en: 'Period',                 sw: 'Kipindi' },

  // ── Fee / Finance strings ─────────────────────────────────────────────────
  'Fee Collected':      { en: 'Fee Collected',          sw: 'Ada Iliyokusanywa' },
  'Outstanding Fees':   { en: 'Outstanding Fees',       sw: 'Ada Zinazodaiwa' },
  'Outstanding Balance':{ en: 'Outstanding Balance',    sw: 'Salio Linalodaiwa' },
  'Amount Paid':        { en: 'Amount Paid',            sw: 'Kiasi Kilicholipwa' },
  'Amount Due':         { en: 'Amount Due',             sw: 'Kiasi Kinachohitajika' },
  'Invoice':            { en: 'Invoice',                sw: 'Ankara' },
  'Receipt':            { en: 'Receipt',                sw: 'Risiti' },
  'Payment':            { en: 'Payment',                sw: 'Malipo' },
  'Payment Method':     { en: 'Payment Method',         sw: 'Njia ya Malipo' },
  'Record Payment':     { en: 'Record Payment',         sw: 'Rekodi Malipo' },
  'Fee Structure':      { en: 'Fee Structure',          sw: 'Muundo wa Ada' },
  'Add Fee Structure':  { en: 'Add Fee Structure',      sw: 'Ongeza Muundo wa Ada' },
  'Generate Invoices':  { en: 'Generate Invoices',      sw: 'Tengeneza Ankara' },
  'Defaulters':         { en: 'Defaulters',             sw: 'Wanaodaiwa Ada' },
  'Fee Balance':        { en: 'Fee Balance',            sw: 'Salio la Ada' },
  'Total Income':       { en: 'Total Income',           sw: 'Jumla ya Mapato' },
  'Total Expenses':     { en: 'Total Expenses',         sw: 'Jumla ya Matumizi' },
  'Cash':               { en: 'Cash',                   sw: 'Fedha Taslimu' },
  'M-Pesa':             { en: 'M-Pesa',                 sw: 'M-Pesa' },
  'Bank Transfer':      { en: 'Bank Transfer',          sw: 'Uhamisho wa Benki' },

  // ── Exam / Results strings ────────────────────────────────────────────────
  'Create Exam':        { en: 'Create Exam',            sw: 'Tengeneza Mtihani' },
  'Exam Name':          { en: 'Exam Name',              sw: 'Jina la Mtihani' },
  'Exam Date':          { en: 'Exam Date',              sw: 'Tarehe ya Mtihani' },
  'Exam Results':       { en: 'Exam Results',           sw: 'Matokeo ya Mtihani' },
  'Publish Results':    { en: 'Publish Results',        sw: 'Chapisha Matokeo' },
  'Enter Marks':        { en: 'Enter Marks',            sw: 'Ingiza Alama' },
  'Total Marks':        { en: 'Total Marks',            sw: 'Jumla ya Alama' },
  'Out of':             { en: 'Out of',                 sw: 'Kati ya' },
  'Score':              { en: 'Score',                  sw: 'Alama' },
  'Pass Mark':          { en: 'Pass Mark',              sw: 'Alama ya Kufaulu' },
  'Highest Score':      { en: 'Highest Score',          sw: 'Alama ya Juu' },
  'Lowest Score':       { en: 'Lowest Score',           sw: 'Alama ya Chini' },
  'Average Score':      { en: 'Average Score',          sw: 'Wastani wa Alama' },
  'Class Average':      { en: 'Class Average',          sw: 'Wastani wa Darasa' },
  'Rank':               { en: 'Rank',                   sw: 'Nafasi' },

  // ── Dashboard metric cards ────────────────────────────────────────────────
  'Active Classes':     { en: 'Active Classes',         sw: 'Madarasa Yanayofanya Kazi' },
  'Fee Collection Rate':{ en: 'Fee Collection Rate',    sw: 'Kiwango cha Ukusanyaji Ada' },
  'This Month':         { en: 'This Month',             sw: 'Mwezi Huu' },
  'This Term':          { en: 'This Term',              sw: 'Muhula Huu' },
  'This Year':          { en: 'This Year',              sw: 'Mwaka Huu' },
  'Today':              { en: 'Today',                  sw: 'Leo' },
  'Yesterday':          { en: 'Yesterday',              sw: 'Jana' },
  'Last 7 Days':        { en: 'Last 7 Days',            sw: 'Siku 7 Zilizopita' },
  'Recent Activity':    { en: 'Recent Activity',        sw: 'Shughuli za Hivi Karibuni' },
  'Quick Actions':      { en: 'Quick Actions',          sw: 'Vitendo vya Haraka' },
  'Overview':           { en: 'Overview',               sw: 'Muhtasari' },
  'Statistics':         { en: 'Statistics',             sw: 'Takwimu' },
  'Analytics':          { en: 'Analytics',              sw: 'Uchanganuzi' },
  'Welcome back':       { en: 'Welcome back',           sw: 'Karibu tena' },
  'School Overview':    { en: 'School Overview',        sw: 'Muhtasari wa Shule' },

  // ── Communication strings ─────────────────────────────────────────────────
  'Send Message':       { en: 'Send Message',           sw: 'Tuma Ujumbe' },
  'New Message':        { en: 'New Message',            sw: 'Ujumbe Mpya' },
  'New Announcement':   { en: 'New Announcement',       sw: 'Tangazo Jipya' },
  'Message':            { en: 'Message',                sw: 'Ujumbe' },
  'Recipients':         { en: 'Recipients',             sw: 'Wapokeaji' },
  'Subject Line':       { en: 'Subject Line',           sw: 'Mstari wa Somo' },
  'Send to All':        { en: 'Send to All',            sw: 'Tuma kwa Wote' },
  'Send to Class':      { en: 'Send to Class',          sw: 'Tuma kwa Darasa' },
  'Unread':             { en: 'Unread',                 sw: 'Haijasomwa' },
  'Read':               { en: 'Read',                   sw: 'Imesomwa' },
  'Inbox':              { en: 'Inbox',                  sw: 'Kikasha cha Barua' },
  'Sent':               { en: 'Sent',                   sw: 'Imetumwa' },
  'Send SMS':           { en: 'Send SMS',               sw: 'Tuma SMS' },
  'SMS Balance':        { en: 'SMS Balance',            sw: 'Salio la SMS' },
  'Message Template':   { en: 'Message Template',       sw: 'Kiolezo cha Ujumbe' },
  'Bulk SMS':           { en: 'Bulk SMS',               sw: 'SMS ya Wingi' },
  'Send to All Parents':{ en: 'Send to All Parents',    sw: 'Tuma kwa Wazazi Wote' },
  'Send to All Teachers':{ en: 'Send to All Teachers',  sw: 'Tuma kwa Walimu Wote' },

  // ── Attendance page headings ──────────────────────────────────────────────
  'Attendance Management': { en: 'Attendance Management', sw: 'Usimamizi wa Mahudhurio' },
  'Daily Attendance':    { en: 'Daily Attendance',       sw: 'Mahudhurio ya Kila Siku' },
  'Monthly Report':      { en: 'Monthly Report',         sw: 'Ripoti ya Kila Mwezi' },
  'Select Class':        { en: 'Select Class',           sw: 'Chagua Darasa' },
  'Select Date':         { en: 'Select Date',            sw: 'Chagua Tarehe' },
  'Select Term':         { en: 'Select Term',            sw: 'Chagua Muhula' },
  'Select Subject':      { en: 'Select Subject',         sw: 'Chagua Somo' },
  'Select Teacher':      { en: 'Select Teacher',         sw: 'Chagua Mwalimu' },
  'Select Student':      { en: 'Select Student',         sw: 'Chagua Mwanafunzi' },
  'All Classes':         { en: 'All Classes',            sw: 'Madarasa Yote' },

  // ── Timetable strings ─────────────────────────────────────────────────────
  'Add Entry':           { en: 'Add Entry',              sw: 'Ongeza Rekodi' },
  'Day':                 { en: 'Day',                    sw: 'Siku' },
  'Time':                { en: 'Time',                   sw: 'Wakati' },
  'Start Time':          { en: 'Start Time',             sw: 'Wakati wa Kuanza' },
  'End Time':            { en: 'End Time',               sw: 'Wakati wa Kumaliza' },
  'Room':                { en: 'Room',                   sw: 'Chumba' },
  'Monday':              { en: 'Monday',                 sw: 'Jumatatu' },
  'Tuesday':             { en: 'Tuesday',                sw: 'Jumanne' },
  'Wednesday':           { en: 'Wednesday',              sw: 'Jumatano' },
  'Thursday':            { en: 'Thursday',               sw: 'Alhamisi' },
  'Friday':              { en: 'Friday',                 sw: 'Ijumaa' },

  // ── Welfare strings ───────────────────────────────────────────────────────
  'Incident':            { en: 'Incident',               sw: 'Tukio' },
  'Incident Type':       { en: 'Incident Type',          sw: 'Aina ya Tukio' },
  'Severity':            { en: 'Severity',               sw: 'Ukali' },
  'Action Taken':        { en: 'Action Taken',           sw: 'Hatua Iliyochukuliwa' },
  'Log Incident':        { en: 'Log Incident',           sw: 'Rekodi Tukio' },
  'Health Record':       { en: 'Health Record',          sw: 'Rekodi ya Afya' },
  'Medical Profile':     { en: 'Medical Profile',        sw: 'Wasifu wa Matibabu' },
  'Allergy':             { en: 'Allergy',                sw: 'Mzio' },
  'Medication':          { en: 'Medication',             sw: 'Dawa' },
  'Leave Request':       { en: 'Leave Request',          sw: 'Ombi la Likizo' },
  'Leave Type':          { en: 'Leave Type',             sw: 'Aina ya Likizo' },
  'Leave Balance':       { en: 'Leave Balance',          sw: 'Salio la Likizo' },
  'Days':                { en: 'Days',                   sw: 'Siku' },

  // ── Transport / Driver strings ────────────────────────────────────────────
  'Route':               { en: 'Route',                  sw: 'Njia' },
  'Route Name':          { en: 'Route Name',             sw: 'Jina la Njia' },
  'Driver':              { en: 'Driver',                 sw: 'Dereva' },
  'Vehicle':             { en: 'Vehicle',                sw: 'Gari' },
  'Pickup':              { en: 'Pickup',                 sw: 'Kupanda' },
  'Drop-off':            { en: 'Drop-off',               sw: 'Kushuka' },
  'Assigned Students':   { en: 'Assigned Students',      sw: 'Wanafunzi Waliowekwa' },
  'Pickup Status':       { en: 'Pickup Status',          sw: 'Hali ya Kupanda' },
  'Picked Up':           { en: 'Picked Up',              sw: 'Amepandishwa' },
  'Missed':              { en: 'Missed',                 sw: 'Amekosa' },

  // ── Library strings ───────────────────────────────────────────────────────
  'Book Title':          { en: 'Book Title',             sw: 'Jina la Kitabu' },
  'Author':              { en: 'Author',                 sw: 'Mwandishi' },
  'ISBN':                { en: 'ISBN',                   sw: 'ISBN' },
  'Issue Book':          { en: 'Issue Book',             sw: 'Toa Kitabu' },
  'Return Book':         { en: 'Return Book',            sw: 'Rudisha Kitabu' },
  'Due Date':            { en: 'Due Date',               sw: 'Tarehe ya Kurejesha' },
  'Fine':                { en: 'Fine',                   sw: 'Faini' },
  'Available':           { en: 'Available',              sw: 'Ipo' },
  'Borrowed':            { en: 'Borrowed',               sw: 'Imekopwa' },
  'Copies':              { en: 'Copies',                 sw: 'Nakala' },

  // ── Settings / Admin strings ──────────────────────────────────────────────
  'School Name':         { en: 'School Name',            sw: 'Jina la Shule' },
  'School Logo':         { en: 'School Logo',            sw: 'Nembo ya Shule' },
  'School Address':      { en: 'School Address',         sw: 'Anwani ya Shule' },
  'School Motto':        { en: 'School Motto',           sw: 'Kauli Mbiu ya Shule' },
  'Current Term':        { en: 'Current Term',           sw: 'Muhula wa Sasa' },
  'Update Settings':     { en: 'Update Settings',        sw: 'Sasisha Mipangilio' },
  'School Settings':     { en: 'School Settings',        sw: 'Mipangilio ya Shule' },
  'System Settings':     { en: 'System Settings',        sw: 'Mipangilio ya Mfumo' },
  'User Account':        { en: 'User Account',           sw: 'Akaunti ya Mtumiaji' },
  'Change Password':     { en: 'Change Password',        sw: 'Badilisha Nywila' },
  'Profile Photo':       { en: 'Profile Photo',          sw: 'Picha ya Wasifu' },
  'Save Profile':        { en: 'Save Profile',           sw: 'Hifadhi Wasifu' },

  // ── IGCSE strings ─────────────────────────────────────────────────────────
  'Session':             { en: 'Session',                sw: 'Kipindi' },
  'Syllabus':            { en: 'Syllabus',               sw: 'Mtaala' },
  'Component':           { en: 'Component',              sw: 'Sehemu' },
  'Grade Boundaries':    { en: 'Grade Boundaries',       sw: 'Mipaka ya Daraja' },
  'Mark Entry':          { en: 'Mark Entry',             sw: 'Kuingiza Alama' },
  'Moderation':          { en: 'Moderation',             sw: 'Usimamizi wa Alama' },

  // ── CBE / Academics strings ───────────────────────────────────────────────
  'Strand':              { en: 'Strand',                 sw: 'Kipengele' },
  'Sub-Strand':          { en: 'Sub-Strand',             sw: 'Kipengele Kidogo' },
  'Learning Outcome':    { en: 'Learning Outcome',       sw: 'Lengo la Kujifunza' },
  'Assessment Type':     { en: 'Assessment Type',        sw: 'Aina ya Tathmini' },
  'Competency':          { en: 'Competency',             sw: 'Uwezo' },
  'Portfolio':           { en: 'Portfolio',              sw: 'Mkoba wa Kazi' },
  'Report Card':         { en: 'Report Card',            sw: 'Ripoti ya Mwanafunzi' },
  'Life Skills':         { en: 'Life Skills',            sw: 'Ustadi wa Maisha' },
  'Career Guidance':     { en: 'Career Guidance',        sw: 'Uelekezaji wa Kazi' },
  'Promotion Rules':     { en: 'Promotion Rules',        sw: 'Sheria za Kupanda Darasa' },
  'Promote Students':    { en: 'Promote Students',       sw: 'Pandisha Wanafunzi' },
  'Scheme of Work':      { en: 'Scheme of Work',         sw: 'Mpango wa Kazi' },
  'Lesson Plan':         { en: 'Lesson Plan',            sw: 'Mpango wa Somo' },
  'SBA':                 { en: 'SBA',                    sw: 'Tathmini ya Shule' },
  'Weekly Plan':         { en: 'Weekly Plan',            sw: 'Mpango wa Wiki' },
  'Objectives':          { en: 'Objectives',             sw: 'Malengo' },
  'Resources':           { en: 'Resources',              sw: 'Rasilimali' },
  'Activities':          { en: 'Activities',             sw: 'Shughuli' },

  // ── Hostel / Canteen / Bursary strings ───────────────────────────────────
  'Hostel':              { en: 'Hostel',                 sw: 'Bweni' },
  'Room Number':         { en: 'Room Number',            sw: 'Nambari ya Chumba' },
  'Capacity':            { en: 'Capacity',               sw: 'Uwezo' },
  'Occupied':            { en: 'Occupied',               sw: 'Imejazwa' },
  'Allocate Room':       { en: 'Allocate Room',          sw: 'Panga Chumba' },
  'Canteen Item':        { en: 'Canteen Item',           sw: 'Bidhaa ya Mkahawa' },
  'Price':               { en: 'Price',                  sw: 'Bei' },
  'Quantity':            { en: 'Quantity',               sw: 'Idadi' },
  'Top Up':              { en: 'Top Up',                 sw: 'Ongeza Salio' },
  'Bursary Award':       { en: 'Bursary Award',          sw: 'Tuzo ya Bursari' },
  'Beneficiary':         { en: 'Beneficiary',            sw: 'Mnufaika' },
  'Sponsor':             { en: 'Sponsor',                sw: 'Mdhamini' },

  // ── Payroll / Appraisal strings ───────────────────────────────────────────
  'Salary':              { en: 'Salary',                 sw: 'Mshahara' },
  'Basic Salary':        { en: 'Basic Salary',           sw: 'Mshahara wa Msingi' },
  'Net Pay':             { en: 'Net Pay',                sw: 'Malipo ya Halisi' },
  'Gross Pay':           { en: 'Gross Pay',              sw: 'Malipo ya Jumla' },
  'Deductions':          { en: 'Deductions',             sw: 'Makato' },
  'Allowances':          { en: 'Allowances',             sw: 'Posho' },
  'Payslip':             { en: 'Payslip',                sw: 'Vocha ya Mshahara' },
  'Run Payroll':         { en: 'Run Payroll',            sw: 'Endesha Mishahara' },
  'Appraisal':           { en: 'Appraisal',              sw: 'Tathmini ya Utendaji' },
  'Rating':              { en: 'Rating',                 sw: 'Kiwango' },
  'Performance':         { en: 'Performance',            sw: 'Utendaji' },

  // ── Gate / Security strings ───────────────────────────────────────────────
  'Visitor':             { en: 'Visitor',                sw: 'Mgeni' },
  'Check In':            { en: 'Check In',               sw: 'Ingia' },
  'Check Out':           { en: 'Check Out',              sw: 'Toka' },
  'Purpose':             { en: 'Purpose',                sw: 'Kusudi' },
  'Host':                { en: 'Host',                   sw: 'Mwenyeji' },
  'Badge':               { en: 'Badge',                  sw: 'Beji' },
  'Gate Log':            { en: 'Gate Log',               sw: 'Kumbukumbu ya Lango' },

  // ── Meetings / Counseling ─────────────────────────────────────────────────
  'Meeting':             { en: 'Meeting',                sw: 'Mkutano' },
  'Book Meeting':        { en: 'Book Meeting',           sw: 'Weka Mkutano' },
  'Meeting Date':        { en: 'Meeting Date',           sw: 'Tarehe ya Mkutano' },
  'Session Notes':       { en: 'Session Notes',          sw: 'Maelezo ya Kipindi' },
  'Counselor':           { en: 'Counselor',              sw: 'Mshauri' },
  'Counseling Session':  { en: 'Counseling Session',     sw: 'Kipindi cha Ushauri' },

  // ── NEMIS / Audit strings ─────────────────────────────────────────────────
  'Export NEMIS':        { en: 'Export NEMIS',           sw: 'Hamisha NEMIS' },
  'NEMIS Number':        { en: 'NEMIS Number',           sw: 'Nambari ya NEMIS' },
  'Validate':            { en: 'Validate',               sw: 'Thibitisha' },
  'Validation':          { en: 'Validation',             sw: 'Uthibitisho' },
  'Issues':              { en: 'Issues',                 sw: 'Matatizo' },
  'Audit Trail':         { en: 'Audit Trail',            sw: 'Njia ya Ukaguzi' },
  'Activity Log':        { en: 'Activity Log',           sw: 'Kumbukumbu ya Shughuli' },
  'User Activity':       { en: 'User Activity',          sw: 'Shughuli za Mtumiaji' },
  'Action':              { en: 'Action',                 sw: 'Kitendo' },
  'Resource':            { en: 'Resource',               sw: 'Rasilimali' },
  'IP Address':          { en: 'IP Address',             sw: 'Anwani ya IP' },

  // ── Inventory strings ─────────────────────────────────────────────────────
  'Item':                { en: 'Item',                   sw: 'Kitu' },
  'Item Name':           { en: 'Item Name',              sw: 'Jina la Kitu' },
  'Stock':               { en: 'Stock',                  sw: 'Hisa' },
  'Reorder Level':       { en: 'Reorder Level',          sw: 'Kiwango cha Kuomba Tena' },
  'In Stock':            { en: 'In Stock',               sw: 'Ipo Stokini' },
  'Out of Stock':        { en: 'Out of Stock',           sw: 'Haina Stoki' },
  'Unit':                { en: 'Unit',                   sw: 'Kitengo' },

  // ── Page headings ─────────────────────────────────────────────────────────
  'Manage Students':     { en: 'Manage Students',        sw: 'Simamia Wanafunzi' },
  'Manage Teachers':     { en: 'Manage Teachers',        sw: 'Simamia Walimu' },
  'Manage Parents':      { en: 'Manage Parents',         sw: 'Simamia Wazazi' },
  'Finance Management':  { en: 'Finance Management',     sw: 'Usimamizi wa Fedha' },
  'Class Management':    { en: 'Class Management',       sw: 'Usimamizi wa Madarasa' },
  'Exam Management':     { en: 'Exam Management',        sw: 'Usimamizi wa Mitihani' },
  'Report Cards':        { en: 'Report Cards',           sw: 'Ripoti za Wanafunzi' },
  'My Dashboard':        { en: 'My Dashboard',           sw: 'Dashibodi Yangu' },
  'Parent Dashboard':    { en: 'Parent Dashboard',       sw: 'Dashibodi ya Mzazi' },
  'Teacher Dashboard':   { en: 'Teacher Dashboard',      sw: 'Dashibodi ya Mwalimu' },
  'Student Dashboard':   { en: 'Student Dashboard',      sw: 'Dashibodi ya Mwanafunzi' },
  'Finance Dashboard':   { en: 'Finance Dashboard',      sw: 'Dashibodi ya Fedha' },

  // ── CBE Analytics ─────────────────────────────────────────────────────────
  'Grade Distribution':  { en: 'Grade Distribution',    sw: 'Usambazaji wa Madaraja' },
  'Class Performance':   { en: 'Class Performance',     sw: 'Utendaji wa Darasa' },
  'Exceeds Expectation': { en: 'Exceeds Expectation',   sw: 'Kuzidi Matarajio' },
  'Meets Expectation':   { en: 'Meets Expectation',     sw: 'Kukidhi Matarajio' },
  'Approaches Expectation':{ en: 'Approaches Expectation', sw: 'Kukaribia Matarajio' },
  'Below Expectation':   { en: 'Below Expectation',     sw: 'Chini ya Matarajio' },
  'Broadsheet':          { en: 'Broadsheet',            sw: 'Jedwali Kubwa' },

  // ── Error / empty messages ────────────────────────────────────────────────
  'Something went wrong': { en: 'Something went wrong',  sw: 'Kuna tatizo limetokea' },
  'Try again':           { en: 'Try again',              sw: 'Jaribu tena' },
  'No students found':   { en: 'No students found',      sw: 'Hakuna wanafunzi' },
  'No teachers found':   { en: 'No teachers found',      sw: 'Hakuna walimu' },
  'No records':          { en: 'No records',             sw: 'Hakuna rekodi' },
  'Are you sure?':       { en: 'Are you sure?',          sw: 'Una uhakika?' },
  'This action cannot be undone': { en: 'This action cannot be undone', sw: 'Kitendo hiki hakiwezi kubatilishwa' },
  'Successfully saved':  { en: 'Successfully saved',     sw: 'Imehifadhiwa' },
  'Successfully deleted':{ en: 'Successfully deleted',   sw: 'Imefutwa' },
  'Successfully updated':{ en: 'Successfully updated',   sw: 'Imesasishwa' },

  // ── Misc / shared ─────────────────────────────────────────────────────────
  'Show':                { en: 'Show',                   sw: 'Onyesha' },
  'Hide':                { en: 'Hide',                   sw: 'Ficha' },
  'per page':            { en: 'per page',               sw: 'kwa ukurasa' },
  'of':                  { en: 'of',                     sw: 'ya' },
  'Page':                { en: 'Page',                   sw: 'Ukurasa' },
  'Total':               { en: 'Total',                  sw: 'Jumla' },
  'Subtotal':            { en: 'Subtotal',               sw: 'Jumla Ndogo' },
  'Income':              { en: 'Income',                 sw: 'Mapato' },
  'Expense':             { en: 'Expense',                sw: 'Matumizi' },
  'Budget':              { en: 'Budget',                 sw: 'Bajeti' },
  'Variance':            { en: 'Variance',               sw: 'Tofauti' },
  'Boys':                { en: 'Boys',                   sw: 'Wavulana' },
  'Girls':               { en: 'Girls',                  sw: 'Wasichana' },

  // ── Sidebar nav — People ─────────────────────────────────────────────────
  'Dashboard':          { en: 'Dashboard',              sw: 'Dashibodi' },
  'Students':           { en: 'Students',               sw: 'Wanafunzi' },
  'Student Report':     { en: 'Student Report',         sw: 'Ripoti ya Mwanafunzi' },
  'Teachers':           { en: 'Teachers',               sw: 'Walimu' },
  'Parents':            { en: 'Parents',                sw: 'Wazazi' },
  'User Management':    { en: 'User Management',        sw: 'Usimamizi wa Watumiaji' },

  // ── Sidebar nav — Academic ───────────────────────────────────────────────
  'Classes & Rooms':    { en: 'Classes & Rooms',        sw: 'Madarasa na Vyumba' },
  'Learning Areas':     { en: 'Learning Areas',         sw: 'Maeneo ya Kujifunza' },
  'Schemes of Work':    { en: 'Schemes of Work',        sw: 'Mpango wa Kazi' },
  'Attendance':         { en: 'Attendance',             sw: 'Mahudhurio' },
  'CBE Assessments':    { en: 'CBE Assessments',        sw: 'Tathmini za CBE' },
  'CBE Report Cards':   { en: 'CBE Report Cards',       sw: 'Ripoti za CBE' },
  'CBE Analytics':      { en: 'CBE Analytics',          sw: 'Takwimu za CBE' },
  'Projects':           { en: 'Projects',               sw: 'Miradi' },
  'Promotion':          { en: 'Promotion',              sw: 'Kupanda Darasa' },
  'Academic Calendar':  { en: 'Academic Calendar',      sw: 'Kalenda ya Masomo' },
  'My Classes':         { en: 'My Classes',             sw: 'Madarasa Yangu' },
  'Grade Book':         { en: 'Grade Book',             sw: 'Kitabu cha Alama' },
  'Lesson Plans':       { en: 'Lesson Plans',           sw: 'Mipango ya Somo' },
  'SBA Marks':          { en: 'SBA Marks',              sw: 'Alama za SBA' },
  'Exams':              { en: 'Exams',                  sw: 'Mitihani' },
  'My Exams':           { en: 'My Exams',               sw: 'Mitihani Yangu' },
  'My Courses':         { en: 'My Courses',             sw: 'Masomo Yangu' },
  'My Attendance':      { en: 'My Attendance',          sw: 'Mahudhurio Yangu' },
  'My Results':         { en: 'My Results',             sw: 'Matokeo Yangu' },
  'Learning Materials': { en: 'Learning Materials',     sw: 'Vifaa vya Kujifunza' },
  'IGCSE Results':      { en: 'IGCSE Results',          sw: 'Matokeo ya IGCSE' },
  'Exam Analytics':     { en: 'Exam Analytics',         sw: 'Takwimu za Mitihani' },
  'Term Reports':       { en: 'Term Reports',           sw: 'Ripoti za Muhula' },
  'NEMIS Export':       { en: 'NEMIS Export',           sw: 'Usafirishaji wa NEMIS' },
  'My Portfolio':       { en: 'My Portfolio',           sw: 'Mkoba wa Kazi' },

  // ── Sidebar nav — Finance ────────────────────────────────────────────────
  'Finance Overview':   { en: 'Finance Overview',       sw: 'Muhtasari wa Fedha' },
  'Income & Expenses':  { en: 'Income & Expenses',      sw: 'Mapato na Matumizi' },
  'Budgets':            { en: 'Budgets',                sw: 'Bajeti' },
  'Vendors & POs':      { en: 'Vendors & POs',          sw: 'Wasambazaji na Amri' },
  'Bank Accounts':      { en: 'Bank Accounts',          sw: 'Akaunti za Benki' },
  'Petty Cash':         { en: 'Petty Cash',             sw: 'Pesa Ndogo' },
  'Assets':             { en: 'Assets',                 sw: 'Mali' },
  'Financial Reports':  { en: 'Financial Reports',      sw: 'Ripoti za Fedha' },
  'Financial Years':    { en: 'Financial Years',        sw: 'Miaka ya Fedha' },
  'Extra Fees':         { en: 'Extra Fees',             sw: 'Ada za Ziada' },
  'My Fees':            { en: 'My Fees',                sw: 'Ada Zangu' },
  'Fee Reminders':      { en: 'Fee Reminders',          sw: 'Vikumbusho vya Ada' },
  'Bursary':            { en: 'Bursary',                sw: 'Bursari' },
  'Inventory':          { en: 'Inventory',              sw: 'Hesabu ya Mali' },
  'Payroll':            { en: 'Payroll',                sw: 'Mishahara' },
  'My Payslips':        { en: 'My Payslips',            sw: 'Vocha za Mishahara' },

  // ── Sidebar nav — Family ─────────────────────────────────────────────────
  'My Children':        { en: 'My Children',            sw: 'Watoto Wangu' },
  'Children Progress':  { en: 'Children Progress',      sw: 'Maendeleo ya Watoto' },
  'Fee Payments':       { en: 'Fee Payments',           sw: 'Malipo ya Ada' },
  'My Alerts':          { en: 'My Alerts',              sw: 'Tahadhari Zangu' },
  'My Transport':       { en: 'My Transport',           sw: 'Usafiri Wangu' },

  // ── Sidebar nav — Schedule ───────────────────────────────────────────────
  'Timetable':          { en: 'Timetable',              sw: 'Ratiba' },
  'My Timetable':       { en: 'My Timetable',           sw: 'Ratiba Yangu' },
  'Assignments':        { en: 'Assignments',            sw: 'Kazi za Nyumbani' },
  'P-T Meetings':       { en: 'P-T Meetings',           sw: 'Mikutano ya Wazazi' },

  // ── Sidebar nav — Welfare ────────────────────────────────────────────────
  'Discipline':         { en: 'Discipline',             sw: 'Nidhamu' },
  'Health':             { en: 'Health',                 sw: 'Afya' },
  'Staff Leave':        { en: 'Staff Leave',            sw: 'Likizo ya Wafanyakazi' },
  'Transport':          { en: 'Transport',              sw: 'Usafiri' },
  'Transport Tracking': { en: 'Transport Tracking',     sw: 'Ufuatiliaji wa Usafiri' },
  'My Route':           { en: 'My Route',               sw: 'Njia Yangu' },
  'Teacher Check-in':   { en: 'Teacher Check-in',       sw: 'Kuingia kwa Mwalimu' },
  'Counseling':         { en: 'Counseling',             sw: 'Ushauri' },
  'Hostel Management':  { en: 'Hostel Management',      sw: 'Usimamizi wa Bweni' },
  'Canteen':            { en: 'Canteen',                sw: 'Mkahawa' },
  'Canteen Balance':    { en: 'Canteen Balance',        sw: 'Salio la Mkahawa' },
  'Appraisals':         { en: 'Appraisals',             sw: 'Tathmini za Utendaji' },
  'My Appraisal':       { en: 'My Appraisal',           sw: 'Tathmini Yangu' },
  'Substitutes':        { en: 'Substitutes',            sw: 'Wabadala' },

  // ── Sidebar nav — Security ───────────────────────────────────────────────
  'Gate Manager':       { en: 'Gate Manager',           sw: 'Msimamizi wa Lango' },
  'Gate Dashboard':     { en: 'Gate Dashboard',         sw: 'Dashibodi ya Lango' },
  'Visitor Log':        { en: 'Visitor Log',            sw: 'Kumbukumbu ya Wageni' },

  // ── Sidebar nav — Messages ───────────────────────────────────────────────
  'Communication':      { en: 'Communication',          sw: 'Mawasiliano' },
  'Messages':           { en: 'Messages',               sw: 'Ujumbe' },
  'Notifications':      { en: 'Notifications',          sw: 'Arifa' },
  'Announcements':      { en: 'Announcements',          sw: 'Matangazo' },
  'SMS Messaging':      { en: 'SMS Messaging',          sw: 'Ujumbe wa SMS' },
  'WhatsApp':           { en: 'WhatsApp',               sw: 'WhatsApp' },
  'Two-Way SMS':        { en: 'Two-Way SMS',            sw: 'SMS ya Njia Mbili' },

  // ── Sidebar nav — Library ────────────────────────────────────────────────
  'Library Catalog':       { en: 'Library Catalog',     sw: 'Orodha ya Maktaba' },
  'My Borrowed Books':     { en: 'My Borrowed Books',   sw: 'Vitabu Nilivyokopa' },
  'Issue / Return':        { en: 'Issue / Return',      sw: 'Toa / Rudisha' },
  'Library Management':    { en: 'Library Management',  sw: 'Usimamizi wa Maktaba' },
  'Library Members':       { en: 'Library Members',     sw: 'Wanachama wa Maktaba' },

  // ── Sidebar nav — Account ────────────────────────────────────────────────
  'Audit Log':          { en: 'Audit Log',              sw: 'Kumbukumbu ya Shughuli' },
  'Settings':           { en: 'Settings',               sw: 'Mipangilio' },
  'My Profile':         { en: 'My Profile',             sw: 'Wasifu Wangu' },

  // ── Sidebar section headers ──────────────────────────────────────────────
  'People':             { en: 'People',                 sw: 'Watu' },
  'Academic':           { en: 'Academic',               sw: 'Masomo' },
  'Finance':            { en: 'Finance',                sw: 'Fedha' },
  'Family':             { en: 'Family',                 sw: 'Familia' },
  'Schedule':           { en: 'Schedule',               sw: 'Ratiba' },
  'Welfare':            { en: 'Welfare',                sw: 'Ustawi' },
  'Security':           { en: 'Security',               sw: 'Usalama' },
  'Library':            { en: 'Library',                sw: 'Maktaba' },
  'Account':            { en: 'Account',                sw: 'Akaunti' },

  // ── legacy keys kept for backward compatibility ──────────────────────────
  dashboard:            { en: 'Dashboard',              sw: 'Dashibodi' },
  students:             { en: 'Students',               sw: 'Wanafunzi' },
  teachers:             { en: 'Teachers',               sw: 'Walimu' },
  parents:              { en: 'Parents',                sw: 'Wazazi' },
  attendance:           { en: 'Attendance',             sw: 'Mahudhurio' },
  fees:                 { en: 'Fees',                   sw: 'Ada' },
  assignments:          { en: 'Assignments',            sw: 'Kazi za Nyumbani' },
  exams:                { en: 'Exams',                  sw: 'Mitihani' },
  results:              { en: 'Results',                sw: 'Matokeo' },
  timetable:            { en: 'Timetable',              sw: 'Ratiba' },
  health:               { en: 'Health',                 sw: 'Afya' },
  transport:            { en: 'Transport',              sw: 'Usafiri' },
  library:              { en: 'Library',                sw: 'Maktaba' },
  communication:        { en: 'Communication',          sw: 'Mawasiliano' },
  announcements:        { en: 'Announcements',          sw: 'Matangazo' },
  my_children:          { en: 'My Children',            sw: 'Watoto Wangu' },
  fee_payment:          { en: 'Fee Payment',            sw: 'Malipo ya Ada' },
  my_courses:           { en: 'My Courses',             sw: 'Masomo Yangu' },
  my_results:           { en: 'My Results',             sw: 'Matokeo Yangu' },
  my_fees:              { en: 'My Fees',                sw: 'Ada Zangu' },
  portfolio:            { en: 'Portfolio',              sw: 'Mkoba wa Kazi' },
  settings:             { en: 'Settings',               sw: 'Mipangilio' },
  profile:              { en: 'My Profile',             sw: 'Wasifu Wangu' },

  // ── Extra strings for dashboards & pages ────────────────────────────────
  'View All':                   { en: 'View All',                   sw: 'Ona Yote' },
  'Quick Access':               { en: 'Quick Access',               sw: 'Ufikiaji wa Haraka' },
  'Pending Assignments':        { en: 'Pending Assignments',        sw: 'Kazi Zinazosubiri' },
  "Today's Classes":            { en: "Today's Classes",            sw: 'Madarasa ya Leo' },
  "Today's Schedule":           { en: "Today's Schedule",           sw: 'Ratiba ya Leo' },
  'No classes today':           { en: 'No classes today',           sw: 'Hakuna madarasa leo' },
  'Enjoy your day!':            { en: 'Enjoy your day!',            sw: 'Furahia siku yako!' },
  'Enjoy your day off!':        { en: 'Enjoy your day off!',        sw: 'Furahia mapumziko yako!' },
  'All caught up!':             { en: 'All caught up!',             sw: 'Umefanya kila kitu!' },
  'No pending assignments':     { en: 'No pending assignments',     sw: 'Hakuna kazi zinazosubiri' },
  "Let's make today a great learning day!": { en: "Let's make today a great learning day!", sw: 'Tufanye leo kuwa siku nzuri ya kujifunza!' },
  'Ready to inspire minds today?': { en: 'Ready to inspire minds today?', sw: 'Uko tayari kuhamasisha akili leo?' },
  "Stay connected with your child's education.": { en: "Stay connected with your child's education.", sw: 'Endelea kuwa karibu na masomo ya mtoto wako.' },
  'Manage teacher records and assignments': { en: 'Manage teacher records and assignments', sw: 'Simamia rekodi na kazi za walimu' },
  'Search teachers by name or employee ID...': { en: 'Search teachers by name or employee ID...', sw: 'Tafuta walimu kwa jina au nambari ya mfanyakazi...' },
  'No teachers found matching your search': { en: 'No teachers found matching your search', sw: 'Hakuna walimu wanaolingana na utafutaji wako' },
  'Add Your First Teacher':     { en: 'Add Your First Teacher',     sw: 'Ongeza Mwalimu wa Kwanza' },
  'No classes assigned yet':    { en: 'No classes assigned yet',    sw: 'Hakuna madarasa yaliyopewa bado' },
  'Employee ID':                { en: 'Employee ID',                sw: 'Nambari ya Mfanyakazi' },
  'Due':                        { en: 'Due',                        sw: 'Muda Umefika' },
  'View Children':              { en: 'View Children',              sw: 'Ona Watoto' },
  'Pay Fees':                   { en: 'Pay Fees',                   sw: 'Lipa Ada' },
  'Class not assigned':         { en: 'Class not assigned',         sw: 'Darasa halijapewa' },
  'No children linked':         { en: 'No children linked',         sw: 'Hakuna watoto waliounganishwa' },
  'Contact the school to link your children to your account.': { en: 'Contact the school to link your children to your account.', sw: 'Wasiliana na shule kuwaunganisha watoto wako kwenye akaunti yako.' },
  'Upcoming Events':            { en: 'Upcoming Events',            sw: 'Matukio Yanayokuja' },
  'Fee Collection':             { en: 'Fee Collection',             sw: 'Ukusanyaji wa Ada' },
  'Manage Users':               { en: 'Manage Users',               sw: 'Simamia Watumiaji' },
  'Search parents...':          { en: 'Search parents...',          sw: 'Tafuta wazazi...' },
  'Search users...':            { en: 'Search users...',            sw: 'Tafuta watumiaji...' },
  'Add User':                   { en: 'Add User',                   sw: 'Ongeza Mtumiaji' },
  'No parents found':           { en: 'No parents found',           sw: 'Hakuna wazazi' },
  'No users found':             { en: 'No users found',             sw: 'Hakuna watumiaji' },
  'Linked Students':            { en: 'Linked Students',            sw: 'Wanafunzi Waliounganishwa' },
  'Fee Account':                { en: 'Fee Account',                sw: 'Akaunti ya Ada' },
  'Total Fees':                 { en: 'Total Fees',                 sw: 'Jumla ya Ada' },
  'Balance':                    { en: 'Balance',                    sw: 'Salio' },
  'Waived':                     { en: 'Waived',                     sw: 'Imesamehewa' },
  'Attendance saved':           { en: 'Attendance saved',           sw: 'Mahudhurio yamehifadhiwa' },
  'Exam Title':                 { en: 'Exam Title',                 sw: 'Kichwa cha Mtihani' },
  'Max Score':                  { en: 'Max Score',                  sw: 'Alama za Juu' },
  'Time Zone':                  { en: 'Time Zone',                  sw: 'Eneo la Wakati' },
  'Language':                   { en: 'Language',                   sw: 'Lugha' },
  'Send Announcement':          { en: 'Send Announcement',          sw: 'Tuma Tangazo' },
  'Compose Message':            { en: 'Compose Message',            sw: 'Tunga Ujumbe' },
  'SMS Templates':              { en: 'SMS Templates',              sw: 'Violezo vya SMS' },
  'SMS History':                { en: 'SMS History',                sw: 'Historia ya SMS' },
  'Sent Messages':              { en: 'Sent Messages',              sw: 'Ujumbe Uliotumwa' },
  'Recipients Count':           { en: 'Recipients Count',           sw: 'Idadi ya Wapokeaji' },
  'Delivered':                  { en: 'Delivered',                  sw: 'Imetolewa' },
  'Loading dashboard...':       { en: 'Loading dashboard...',       sw: 'Inapakia dashibodi...' },
  'Total:':                     { en: 'Total:',                     sw: 'Jumla:' },
  'Manage parent accounts and link them to students': { en: 'Manage parent accounts and link them to students', sw: 'Simamia akaunti za wazazi na uwaunganishe na wanafunzi' },
  'Total Parents':              { en: 'Total Parents',              sw: 'Jumla ya Wazazi' },
  'With Linked Children':       { en: 'With Linked Children',       sw: 'Wenye Watoto Waliounganishwa' },
  'Without Children':           { en: 'Without Children',           sw: 'Bila Watoto' },
  'Add Your First Parent':      { en: 'Add Your First Parent',      sw: 'Ongeza Mzazi wa Kwanza' },
  'Relationship':               { en: 'Relationship',               sw: 'Uhusiano' },
  'Children':                   { en: 'Children',                   sw: 'Watoto' },
  'loading...':                 { en: 'loading...',                 sw: 'inapakia...' },
  'Loading finance dashboard...': { en: 'Loading finance dashboard...', sw: 'Inapakia dashibodi ya fedha...' },
  'Here is your financial overview for today.': { en: 'Here is your financial overview for today.', sw: 'Hapa kuna muhtasari wako wa fedha wa leo.' },
  'Finance Officer':            { en: 'Finance Officer',            sw: 'Afisa wa Fedha' },
  'Net Position':               { en: 'Net Position',               sw: 'Hali ya Fedha' },
  'Collection Rate':            { en: 'Collection Rate',            sw: 'Kiwango cha Ukusanyaji' },
  'Bank Balance':               { en: 'Bank Balance',               sw: 'Salio la Benki' },
  'Pending Expenses':           { en: 'Pending Expenses',           sw: 'Matumizi Yanayosubiri' },
  'Expenses':                   { en: 'Expenses',                   sw: 'Matumizi' },
  'View Details':               { en: 'View Details',               sw: 'Ona Maelezo' },
  'No pending expenses':        { en: 'No pending expenses',        sw: 'Hakuna matumizi yanayosubiri' },
  'Collected':                  { en: 'Collected',                  sw: 'Iliyokusanywa' },
  'Outstanding':                { en: 'Outstanding',                sw: 'Iliyobaki' },
  'Manage users and their roles': { en: 'Manage users and their roles', sw: 'Simamia watumiaji na majukumu yao' },
  'Add Your First User':        { en: 'Add Your First User',        sw: 'Ongeza Mtumiaji wa Kwanza' },
  'Last Login':                 { en: 'Last Login',                 sw: 'Kuingia Mara ya Mwisho' },
  'Total Users':                { en: 'Total Users',                sw: 'Jumla ya Watumiaji' },
  'Admins':                     { en: 'Admins',                     sw: 'Wasimamizi' },
  'Finance Officers':           { en: 'Finance Officers',           sw: 'Maafisa wa Fedha' },
  'Teacher':                    { en: 'Teacher',                    sw: 'Mwalimu' },
  'Student':                    { en: 'Student',                    sw: 'Mwanafunzi' },
  'Parent':                     { en: 'Parent',                     sw: 'Mzazi' },
  'No.':                        { en: 'No.',                        sw: 'Na.' },
  'ID':                         { en: 'ID',                         sw: 'Nambari' },
  'School Info':                { en: 'School Info',                sw: 'Taarifa za Shule' },
  'Contact & Address':          { en: 'Contact & Address',          sw: 'Mawasiliano na Anwani' },
  'System':                     { en: 'System',                     sw: 'Mfumo' },
  'School Information':         { en: 'School Information',         sw: 'Taarifa za Shule' },
  'Manage system configuration and preferences': { en: 'Manage system configuration and preferences', sw: 'Simamia usanidi na mapendeleo ya mfumo' },
  'System Preferences':         { en: 'System Preferences',         sw: 'Mapendeleo ya Mfumo' },
  'Saving...':                  { en: 'Saving...',                  sw: 'Inahifadhi...' },
  'Teacher Check-in Hours':     { en: 'Teacher Check-in Hours',     sw: 'Masaa ya Kuingia kwa Mwalimu' },
  'Timezone':                   { en: 'Timezone',                   sw: 'Eneo la Wakati' },
  'Currency':                   { en: 'Currency',                   sw: 'Sarafu' },
  'Date Format':                { en: 'Date Format',                sw: 'Muundo wa Tarehe' },
  'Time Format':                { en: 'Time Format',                sw: 'Muundo wa Wakati' },
  'Website':                    { en: 'Website',                    sw: 'Tovuti' },
  'City':                       { en: 'City',                       sw: 'Mji' },
  'County/State':               { en: 'County/State',               sw: 'Kaunti/Jimbo' },
  'Postal Code':                { en: 'Postal Code',                sw: 'Nambari ya Posta' },
  'Current Academic Year':      { en: 'Current Academic Year',      sw: 'Mwaka wa Masomo wa Sasa' },
  'School Code':                { en: 'School Code',                sw: 'Msimbo wa Shule' },
  'Total Records':              { en: 'Total Records',              sw: 'Jumla ya Rekodi' },
  'Track and manage student attendance': { en: 'Track and manage student attendance', sw: 'Fuatilia na usimamie mahudhurio ya wanafunzi' },
  "Today's Attendance Rate":    { en: "Today's Attendance Rate",    sw: 'Kiwango cha Mahudhurio ya Leo' },
  'Overall attendance rate':    { en: 'Overall attendance rate',    sw: 'Kiwango cha mahudhurio kwa jumla' },
  "Mark Today's Attendance":    { en: "Mark Today's Attendance",    sw: 'Rekodi Mahudhurio ya Leo' },
  'Download Monthly Report':    { en: 'Download Monthly Report',    sw: 'Pakua Ripoti ya Mwezi' },
  'Send Absence Notifications': { en: 'Send Absence Notifications', sw: 'Tuma Arifa za Kutokuwepo' },
  'Monthly Attendance Report':  { en: 'Monthly Attendance Report',  sw: 'Ripoti ya Mahudhurio ya Mwezi' },
};

interface LanguageStore {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key: string) => {
        const lang = get().language;
        return translations[key]?.[lang] ?? key.replace(/_/g, ' ');
      },
    }),
    { name: 'skulmanager-language', storage: createJSONStorage(() => zustandSafeStorage) }
  )
);
