CREATE TABLE IF NOT EXISTS students (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) UNIQUE,
  admission_number VARCHAR(50) UNIQUE NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  gender ENUM('male', 'female', 'other'),
  blood_group VARCHAR(5),
  religion VARCHAR(50),
  caste VARCHAR(50),
  category ENUM('general', 'obc', 'sc', 'st', 'other'),
  aadhar_number VARCHAR(12),
  roll_number VARCHAR(20),
  class_id VARCHAR(36),
  section_id VARCHAR(36),
  parent_id VARCHAR(36),
  joining_date DATE,
  admission_date DATE,
  status ENUM('active', 'inactive', 'suspended', 'transferred', 'graduated') DEFAULT 'active',
  is_new_admission BOOLEAN DEFAULT TRUE,
  medical_notes TEXT,
  emergency_contact JSON,
  address TEXT,
  city VARCHAR(100),
  state VARCHAR(100),
  pincode VARCHAR(10),
  profile_photo_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_admission_number (admission_number),
  INDEX idx_class_section (class_id, section_id),
  INDEX idx_parent_id (parent_id),
  INDEX idx_status (status),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS student_documents (
  id VARCHAR(36) PRIMARY KEY,
  student_id VARCHAR(36) NOT NULL,
  document_type ENUM('birth_certificate', 'transfer_certificate', 'medical', 'address_proof', 'photo', 'other') NOT NULL,
  file_url VARCHAR(500) NOT NULL,
  file_name VARCHAR(255),
  file_size INT,
  mime_type VARCHAR(100),
  uploaded_by VARCHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_student_id (student_id),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS student_promotions (
  id VARCHAR(36) PRIMARY KEY,
  student_id VARCHAR(36) NOT NULL,
  from_class_id VARCHAR(36),
  to_class_id VARCHAR(36),
  session VARCHAR(20) NOT NULL,
  result ENUM('promoted', 'detained', 'transferred') NOT NULL,
  percentage DECIMAL(5,2),
  remarks TEXT,
  promoted_by VARCHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_student_id (student_id),
  INDEX idx_session (session),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (promoted_by) REFERENCES users(id) ON DELETE SET NULL
);
